#include "gfx.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void gfx_generate_rgb_framebuffer(computer_t *computer) {
	for (int y = 0; y < SCREEN_HEIGHT; y++) {
		for (int x = 0; x < SCREEN_WIDTH; x++) {
			color_t pixel = computer->ram->framebuffer.data[y * SCREEN_WIDTH + x];
			computer->rgb_framebuffer[y * SCREEN_WIDTH + x] = computer->ram->palette.colors[pixel];
		}
	}
}

// TODO: don't do linear search
// TODO: get the closes possible color to be able to load any image
color_t gfx_rgb_color_to_color(palette_t *palette, rgb_color_t rgb_color, color_t undefined_color) {
	for (size_t i = 0; i < PALETTE_SIZE; i++) {
		if (palette->colors[i].r == rgb_color.r && palette->colors[i].g == rgb_color.g && palette->colors[i].b == rgb_color.b) {
			return i;
		}
	}

	printf("Color not found\n");
	return undefined_color;
}

void gfx_clear(surface_t surface, color_t color) {
	for (int y = 0; y < surface.height; y++) {
		for (int x = 0; x < surface.width; x++) {
			surf_set_pixel(surface, x, y, color);
		}
	}
}

// TODO: make these geometry functions take any uint8_t array and a vec2i of size
// so they can be used both for the framebuffer and the spritesheet
void gfx_draw_rect(surface_t surf, rect_t rect, color_t color) {
	for (int j = rect.x; j < rect.x+rect.w; j++) {
		surf_set_pixel(surf, j, rect.y, color);
	}

	for (int j = rect.x; j < rect.x+rect.w; j++) {
		surf_set_pixel(surf, j, rect.y+rect.h-1, color);
	}

	for (int i = rect.y; i < rect.y+rect.h; i++) {
		surf_set_pixel(surf, rect.x, i, color);
	}

	for (int i = rect.y; i < rect.y+rect.h; i++) {
		surf_set_pixel(surf, rect.x+rect.w - 1, i, color);
	}
}

void gfx_draw_filled_rect(surface_t surf, rect_t rect, color_t color) {
	for (int i = rect.y; i < rect.y+rect.h; i++) {
		for (int j = rect.x; j < rect.x+rect.w; j++) {
			surf_set_pixel(surf, j, i, color);
		}
	}
}

// Using Bresemham's line algorithm
void gfx_draw_line(surface_t surf, point_t start, point_t end, color_t color) {
	int x1 = start.x;
	int y1 = start.y;
	int x2 = end.x;
	int y2 = end.y;
	
	int dx = abs(x2 - x1);
	int dy = abs(y2 - y1);
	int step_x = (x1 < x2) ? 1 : -1;
	int step_y = (y1 < y2) ? 1 : -1;
	int error = dx - dy;
	
	while (true) {
		surf_set_pixel(surf, x1, y1, color);
		
		if (x1 == x2 && y1 == y2) break;
		
		int e2 = 2 * error;
		if (e2 > -dy) {
			error -= dy;
			x1 += step_x;
		}
		if (e2 < dx) {
			error += dx;
			y1 += step_y;
		}
	}
}

// Midpoint circle algorithm
// TODO: adopt for ellipses
// TODO: filled bool
void gfx_draw_circle(surface_t surf, point_t pos, int radius, color_t color) {
	int x = pos.x;
	int y = pos.y;
	
	// Initial 4 points
	surf_set_pixel(surf, x + radius, y, color);
	surf_set_pixel(surf, x - radius, y, color);
	surf_set_pixel(surf, x, y + radius, color);
	surf_set_pixel(surf, x, y - radius, color);

	int x_offset = radius;
	int y_offset = 0;

	int d = 1 - radius;

	while (x_offset > y_offset) {
		y_offset++;
		
		if (d <= 0) {
			d = d + 2 * y_offset + 1;
		} else {
			x_offset--;
			d = d + 2 * (y_offset - x_offset) + 1;
		}
		
		if (x_offset < y_offset) {
			break;
		}

		surf_set_pixel(surf, x + x_offset, y + y_offset, color);
		surf_set_pixel(surf, x - x_offset, y + y_offset, color);
		surf_set_pixel(surf, x + x_offset, y - y_offset, color);
		surf_set_pixel(surf, x - x_offset, y - y_offset, color);

		if (x_offset != y_offset) {
			surf_set_pixel(surf, x + y_offset, y + x_offset, color);
			surf_set_pixel(surf, x - y_offset, y + x_offset, color);
			surf_set_pixel(surf, x + y_offset, y - x_offset, color);
			surf_set_pixel(surf, x - y_offset, y - x_offset, color);
		}
	}
}

// This function is taken from https://zingl.github.io/bresenham.html
void gfx_draw_ellipse(surface_t surf, rect_t bound, color_t color) {
	int x0 = rect_topleft(bound).x;
	int y0 = rect_topleft(bound).y;
	int x1 = rect_bottomright(bound).x;
	int y1 = rect_bottomright(bound).y;

	int a = abs(x1-x0), b = abs(y1-y0), b1 = b&1; /* values of diameter */
	long dx = 4*(1-a)*b*b, dy = 4*(b1+1)*a*a; /* error increment */
	long err = dx+dy+b1*a*a, e2; /* error of 1.step */

	if (x0 > x1) { x0 = x1; x1 += a; } /* if called with swapped points */
	if (y0 > y1) y0 = y1; /* .. exchange them */
	y0 += (b+1)/2; y1 = y0-b1; /* starting pixel */
	a *= 8*a; b1 = 8*b*b;

	do {
		surf_set_pixel(surf, x1, y0, color); /*   I. Quadrant */
		surf_set_pixel(surf, x0, y0, color); /*  II. Quadrant */
		surf_set_pixel(surf, x0, y1, color); /* III. Quadrant */
		surf_set_pixel(surf, x1, y1, color); /*  IV. Quadrant */
		e2 = 2*err;
		if (e2 <= dy) { y0++; y1--; err += dy += a; }  /* y step */ 
		if (e2 >= dx || 2*err > dy) { x0++; x1--; err += dx += b1; } /* x step */
	} while (x0 <= x1);
	
	while (y0-y1 < b) { /* too early stop of flat ellipses a=1 */
		surf_set_pixel(surf, x0-1, y0, color); /* -> finish tip of ellipse */
		surf_set_pixel(surf, x1+1, y0++, color); 
		surf_set_pixel(surf, x0-1, y1, color);
		surf_set_pixel(surf, x1+1, y1--, color); 
	}
}

// This function was generated by ChatGPT based on the previous function
void gfx_draw_filled_ellipse(surface_t surf, rect_t bound, color_t color) {
	int x0 = rect_topleft(bound).x;
	int y0 = rect_topleft(bound).y;
	int x1 = rect_bottomright(bound).x;
	int y1 = rect_bottomright(bound).y;

	int a = abs(x1 - x0);
	int b = abs(y1 - y0);
	int b1 = b & 1;

	long dx = 4 * (1 - a) * b * b;
	long dy = 4 * (b1 + 1) * a * a;
	long err = dx + dy + b1 * a * a;
	long e2;

	if (x0 > x1) {
		x0 = x1;
		x1 += a;
	}

	if (y0 > y1)
		y0 = y1;

	y0 += (b + 1) / 2;
	y1 = y0 - b1;

	a *= 8 * a;
	b1 = 8 * b * b;

	do {
		// Fill horizontal spans instead of edge pixels
		for (int x = x0; x <= x1; x++) {
			surf_set_pixel(surf, x, y0, color);
			surf_set_pixel(surf, x, y1, color);
		}

		e2 = 2 * err;

		if (e2 <= dy) {
			y0++;
			y1--;
			err += dy += a;
		}

		if (e2 >= dx || 2 * err > dy) {
			x0++;
			x1--;
			err += dx += b1;
		}

	} while (x0 <= x1);

	while (y0 - y1 < b) {
		for (int x = x0 - 1; x <= x1 + 1; x++) {
			surf_set_pixel(surf, x, y0, color);
			surf_set_pixel(surf, x, y1, color);
		}

		y0++;
		y1--;
	}
}

color_t gfx_spritesheet_get_pixel(spritesheet_t *spritesheet, point_t point) {
	// TODO: clip the wanted rect instead of this check ???
	if (point_in_rect(point, RECT(0, 0, SPRITESHEET_WIDTH, SPRITESHEET_HEIGHT))) {
		return spritesheet->data[point.y * SPRITESHEET_WIDTH + point.x];
	}
	// TODO: should this be 0 or COLOR_NONE ???
	return COLOR_NONE;
}

void gfx_spritesheet_set_pixel(spritesheet_t *spritesheet, point_t point, color_t color) {
	if (point_in_rect(point, RECT(0, 0, SPRITESHEET_WIDTH, SPRITESHEET_HEIGHT))) {
		spritesheet->data[point.y * SPRITESHEET_WIDTH + point.x] = color;
	}
}

rect_t sprite_index_to_spritesheet_rect(int sprite_index, int w, int h) {
	rect_t rect = {
		.x = (sprite_index % SPRITES_PER_ROW) * SPRITE_WIDTH,
		.y = (sprite_index / SPRITES_PER_ROW) * SPRITE_HEIGHT,
		.w = w * SPRITE_WIDTH,
		.h = h * SPRITE_HEIGHT,
	};

	return rect;
}

// TODO: make everything take a bounds rect, anything outside of it will get clipped
// either that or it's state-based, where by default the clip rect is the screen and you can set it
// but who likes unnecessary state machines
// I can actually just make a macro or wrapper function for clip bounds being the screen

void gfx_copy_surface_rect(surface_t dest, surface_t src, point_t dest_pos, rect_t source_rect, color_t color_key) {
	for (int i = 0; i < source_rect.h; i++) {
		for (int j = 0; j < source_rect.w; j++) {
			color_t color = surf_get_pixel(src, source_rect.x + j, source_rect.y + i);
			if (color != color_key) {
				surf_set_pixel(dest, dest_pos.x + j, dest_pos.y + i, color);
			}
		}
	}
}

void gfx_draw_surface_rect(framebuffer_t *fb, surface_t surf, point_t dest_pos, rect_t source_rect, color_t color_key) {
	for (int i = 0; i < source_rect.h; i++) {
		for (int j = 0; j < source_rect.w; j++) {
			color_t color = surf_get_pixel(surf, source_rect.x + j, source_rect.y + i);
			if (color != color_key) {
				gfx_set_pixel(fb, dest_pos.x + j, dest_pos.y + i, color);
			}
		}
	}
}

void gfx_draw_spritesheet_rect(ram_t *ram, point_t pos, rect_t rect, color_t color_key) {
	gfx_draw_surface_rect(&ram->framebuffer, SPR_SURF(ram->spritesheet.data), pos, rect, color_key);
}

void gfx_draw_surface_pro(framebuffer_t *fb, surface_t surf, rect_t source_rect, rect_t dest_rect, color_t color_key, rect_t clip_rect) {
	rect_t clipped_dest_rect = rect_clip(clip_rect, dest_rect);

	for (int y = 0; y < clipped_dest_rect.h; y++) {
		for (int x = 0; x < clipped_dest_rect.w; x++) {
			// Calculate normalized coords
			float u = (float)(x + clipped_dest_rect.x - dest_rect.x) / (float)dest_rect.w;
			float v = (float)(y + clipped_dest_rect.y - dest_rect.y) / (float)dest_rect.h;

			// Then convert to source coords
			int source_x = source_rect.x + u * source_rect.w;
			int source_y = source_rect.y + v * source_rect.h;

			// TODO: look at this again later
			// It's the same concept but only integer math so it scales less flexibally but also does not have incorrect pixels
			// and it's faster
			// I should also look into fixed point arithmatic, the 2 lines below are just integer math but that's probably not sufficient
			// int source_x = source_rect.x + (x * source_rect.w) / dest_rect.w;
			// int source_y = source_rect.y + (y * source_rect.h) / dest_rect.h;

			color_t color = surf_get_pixel(surf, source_x, source_y);
			
			if (color != color_key) {
				gfx_set_pixel(fb, clipped_dest_rect.x + x, clipped_dest_rect.y + y, color);
			}
		}
	}
}

void gfx_draw_spritesheet_pro(ram_t *ram, rect_t source_rect, rect_t dest_rect, color_t color_key, rect_t clip_rect) {
	gfx_draw_surface_pro(&ram->framebuffer, SPR_SURF(ram->spritesheet.data), source_rect, dest_rect, color_key, clip_rect);
}

// TODO: implement flip_x, flip_y
void gfx_draw_sprites(ram_t *ram, int index, point_t pos, int width, int height) {
	rect_t rect = sprite_index_to_spritesheet_rect(index, width, height);
	
	gfx_draw_spritesheet_rect(ram, pos, rect, ram->sprites[index].color_key);
}

void gfx_draw_sprites_page(ram_t *ram, int page_index, int relative_index, point_t pos, int width, int height) {
	int absolute_index = page_index * SPRITES_PER_PAGE + relative_index;

	rect_t rect = sprite_index_to_spritesheet_rect(absolute_index, width, height);

	gfx_draw_spritesheet_rect(ram, pos, rect, ram->sprites[absolute_index].color_key);
}

// TODO: support clipping so the background in the skin is actually used
void gfx_draw_map(ram_t *ram, int layer_index, point_t pos, rect_t section, float scale, color_t color_key, rect_t clip_rect, uint32_t mask) {
	section = rect_clip(RECT(0, 0, MAP_WIDTH, MAP_HEIGHT), section);

	for (int i = section.y; i < section.y + section.h; i++) {
		for (int j = section.x; j < section.x + section.w; j++) {
			// TODO: if an empty sprite is drawn, one blue pixel should be drawn like in PICO-8
			// that's to signify it's not sprite 0
			// also erasing should be a thing
			// or maybe placing anything in the map editor while the top left origin of the in frame rect in sprites is 0, 0 will result in all sprites placed being 0??? idk

			int sprite_index = ram->map.layers[layer_index].data[i * MAP_WIDTH + j];
			if (mask != 0b11111111111111111111111111111111 && (ram->sprites[sprite_index].flags & mask) == 0) {
				continue;
			}

			rect_t source_rect = sprite_index_to_spritesheet_rect(sprite_index, 1, 1);

			int scaled_sprite_width = (int)(SPRITE_WIDTH * scale);
			int scaled_sprite_height = (int)(SPRITE_HEIGHT * scale);
			
			rect_t dest_rect = RECT(
				pos.x + j * scaled_sprite_width,
				pos.y + i * scaled_sprite_height,
				scaled_sprite_width,
				scaled_sprite_height
			);

			// TODO: not sure about the performance implications of just passing the clip rect to the spritesheet function
			// because now its still trying to draw each tile and ideally tiles should be culled beforehand
			// but I think until it gives problems this is alright
			gfx_draw_spritesheet_pro(ram, source_rect, dest_rect, color_key, clip_rect);
		}
	}
}

ARRAY_DEFINE(point_t);
void gfx_flood_fill(surface_t surface, point_t point, color_t color, rect_t limit) {
	color_t start_color = surf_get_pixel(surface, point.x, point.y);

	if (color == start_color) {
		return;
	}

	point_t directions[] = {{1, 0}, {-1, 0}, {0, 1}, {0, -1}};

	point_t_array_t stack = {0};
	array_init(&stack, get_heap_allocator());

	array_push(&stack, point);

	while (stack.len > 0) {
		point_t current = array_pop(&stack);

		if (point_in_rect(current, limit)) {
			surf_set_pixel(surface, current.x, current.y, color);
		}

		// Iterate directions
		for (int i = 0; i < 4; i++) {
			point_t new_point = {
				current.x + directions[i].x,
				current.y + directions[i].y,
			};

			if (point_in_rect(new_point, limit) && surf_get_pixel(surface, new_point.x, new_point.y) == start_color) {
				surf_set_pixel(surface, new_point.x, new_point.y, color);
				
				array_push(&stack, new_point);
			}
		}
	}

	array_deinit(&stack);
}

// TODO: for each font set a color_key and divider color so you can have funky fonts idk
void gfx_draw_string(ram_t *ram, int font_index, string_t string, point_t pos, int color) {
	font_t *font = &ram->fonts[font_index];

	int new_x = pos.x;
	int new_y = pos.y;

	surface_t surface = surface = SPR_SURF(ram->spritesheet.data);
	if (font->surface == SURFACE_SKIN) {
		surface = SKIN_SURF(ram->skin.data);
	}

	for (size_t i = 0; i < string.len; i++) {
		// Commented this out for now, might add it back later not sure yet
		if (string.data[i] == '\n') {
			new_x = pos.x;
			new_y += font->height + font->vertical_space;
			continue;
		}

		if (string.data[i] == '\t') {
			const int TAB_SIZE = 4;
			new_x += (font->widths[' ' - VISIBLE_CHARACTERS_START] + font->horizontal_space) * TAB_SIZE;
			continue;
		}

		// Inline sprites, will probably remove in favor of making 256 characters available in the fonts
		// if (string.data[i] == '`') {
		// 	int sprite_index = 0;

		// 	// Read the digits after
		// 	size_t index = i + 1;
		// 	while (string.data[index] >= '0' && string.data[index] <= '9') {
		// 		sprite_index *= 10;
		// 		sprite_index += string.data[index] - '0';

		// 		index++;
		// 	}

		// 	gfx_draw_sprites(ram, sprite_index, POINT(new_x, new_y), font->sprite_width, font->sprite_height);
		// 	new_x += 16 + font->horizontal_space;

		// 	i = index - 1;

		// 	continue;
		// }

		int char_index = string.data[i] - VISIBLE_CHARACTERS_START;
		
		rect_t rect = {
			.x = font->start_pos.x + (char_index % font->columns) * font->char_max_width,
			.y = font->start_pos.y + (char_index / font->columns) * font->char_max_height,
			.w = font->char_max_width,
			.h = font->char_max_height,
		};

		for (int i = 0; i < rect.h; i++) {
			for (int j = 0; j < rect.w; j++) {
				color_t pixel_color = surf_get_pixel(surface, rect.x + j, rect.y + i);

				if (pixel_color != font->color_key && pixel_color != font->seperator_color) {
					if (color != COLOR_NONE) {
						gfx_set_pixel(&ram->framebuffer, new_x + j, new_y + i, color);
					} else {
						gfx_set_pixel(&ram->framebuffer, new_x + j, new_y + i, pixel_color);
					}
				}
			}
		}

		new_x += font->widths[string.data[i] - VISIBLE_CHARACTERS_START] + font->horizontal_space;
	}
}

void gfx_draw_text(ram_t *ram, int font_index, const char text[], point_t pos, int color) {
	size_t len = strlen(text);
	
	// Dirty typecast, TODO look at this again maybe
	gfx_draw_string(ram, font_index, (string_t){.data = (char *)text, .len = len}, pos, color);
}
